modality: "vision"
dt: 0.05
num_steps_simulation: 120
num_steps_horizon: 11
x_init:
  0: {value: 0, rand: false, min: 0., max: 0.}
  1: {value: 0, rand: false, min: 0., max: 0.}
  2: {value: 0, rand: false}
  3: {value: 0, rand: false}
  4: {value: 0, rand: false}
  5: {value: 0, rand: false}
num_simulations: 2
plot: true
save_images: false
old: false
use_nominal_plant: false
control_type: "mpc"

constraints:
  use_inputs_constraints: false
  force_limits: [7, 13]
  torque_limits: [0, 0.]

x_ref:
  specs:
    # 0: { type: sine, amplitude: 0.4, freq_hz: 0.2, phase: 0 }
    # 1: { type: sine_cosine, amplitude: 0.4, freq_hz: 0.2, phase: 0 }
    0: { type: constant, value: 0.2, rand: false, min: -0.25, max: 0.25 }
    1: { type: constant, value: 0.2, rand: false, min: -0.25, max: 0.25 }

cost:
  R: [0.01, 0.01]
  S: [0.0, 0.0]
  Qz: 1
  only_position: false
  Pz: 5

solver_options:
  nlp_solver_type: "SQP_RTI"
  qp_solver_iter_max: 100
  qp_tol: 1.0e-8
  qp_warm_start: true
  regularization: 1.0e-4
  print_level: 0