modality: "sensor"
dt: 0.01
num_steps_simulation: 300
num_steps_horizon: 50
x_init:
  0: { value: -0.15, rand: false, min: -0.25, max: 0.25 }
  1: { value: -0.15, rand: false, min: -0.25, max: 0.25 }
  2: { value: 0, rand: false }
  3: { value: 0, rand: false }
  4: { value: 0, rand: false }
  5: { value: 0, rand: false }
  6: { value: 0, rand: false }
  7: { value: 0, rand: false }
  8: { value: 0, rand: false }
  9: { value: 0, rand: false }
  10: { value: 0, rand: false }
  11: { value: 0, rand: false }
num_simulations: 1
plot: true
render_images: false
use_nominal_plant: false
control_type: "mpc"

constraints:
  use_inputs_constraints: false
  force_limits: [8, 12]
  torque_limits: [-2, 2]

x_ref:
  specs:
    0: { type: constant, value: 0.4, rand: false, min: -0.25, max: 0.25 }
    1: { type: constant, value: 0.4, rand: false, min: -0.25, max: 0.25 }
    2: { type: constant, value: 0.3, rand: false, min: -0.25, max: 0.25 }

cost:
  R: [0.001, 0.001, 0.001, 0.001]
  S: [0.01, 0.01, 0.01, 0.01]
  Q_positions: 3
  Q_velocities: 0.5
  P_positions: 3
  P_velocities: 3

solver_options:
   nlp_solver_type: "SQP_RTI"
   qp_solver_iter_max: 100
   qp_tol: 1.0e-8
   qp_warm_start: true
   regularization: 1.0e-8
   print_level: 0